version: "3.7"

services:
  by-weekly:
    build: .
    command:
      - "bin/run"
    ports:
      - 8001:8001
    # environment:
    #   WATCH: "1"
    #   ENVIRONMENT: "development"
    volumes:
      - ../by-weekly/src:/opt/by-weekly/src
      - ../by-weekly/dist:/opt/by-weekly/dist
      - ../by-weekly/bin:/opt/by-weekly/bin
      - ../by-weekly/.babelrc:/opt/by-weekly/.babelrc
      - ../by-weekly/.eslintrc:/opt/by-weekly/.eslintrc
      - ../by-weekly/package.json:/opt/by-weekly/package.json
      - ../by-weekly/package-lock.json:/opt/by-weekly/package-lock.json
      - ../by-weekly/webpack.config.common.js:/opt/by-weekly/webpack.config.common.js
      - ../by-weekly/webpack.config.dev.js:/opt/by-weekly/webpack.config.dev.js
